name: networking
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  flutter_bloc:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
