name: bibliobook
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # exernal and web
  webview_flutter: ^4.0.7
  share_plus: ^6.3.2
  url_launcher: ^6.1.10
  # Auth buttons
  auth_buttons: ^3.0.0
  font_awesome_flutter: ^10.4.0
  # State management packages
  provider:
  flutter_bloc:
  equatable:
  flutter_shimmer:
  # Firebase and auth packages
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0
  flutterfire_ui: ^0.4.3+20
  google_sign_in:
  # storage and files
  path_provider: ^2.0.14
  image_picker: ^0.8.7+2
  video_player: ^2.6.1
  record: ^4.4.4
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/app_icon.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
